[package]
name = "ferrum_desktop"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "ferrum"
path = "src/main.rs"

[dependencies]
ferrum_core.workspace = true

tauri = { version = "2.9.4", features = [] }

[build-dependencies]
tauri-build = { version = "2.5.2", features = [] }
