[workspace]
name = "ferrum"
members = [
    "ferrum_core",
    "ferrum_desktop"
]
resolver = "2"

[workspace.dependencies]
ferrum_core = { version = "0.1.0", path = "ferrum_core"}

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Johannes Breitenbach"]
license = "MIT"
