[package]
name = "ferrum_shell"
version = "0.1.0"
edition = "2021"

[dependencies]
wry = "0.53.5"
tao = "0.34.5"
gtk = "0.18.2"

reqwest = { version = "0.12", features = ["rustls-tls"] }
tokio = { version = "1", features = ["full"] }

# Logging
log = "0.4"
env_logger = "0.11"